server: ../bin/server
telegram: ../bin/telegram
scheduler: ../bin/scheduler
whisper: whisper-server --model /opt/homebrew/share/whisper-cpp/ggml-base.bin --port 8080
kokoro: cd /Users/filippo/code/Kokoro-FastAPI && ESPEAK_DATA_PATH=$(brew --prefix)/share/espeak-ng-data ./start-cpu.sh
